import { EnemyType } from "../types/EnemyType";

export const ENEMIES: EnemyType[] = [
  {
    id: "1",
    name: "Bandido",
    attack: 3,
    magic: 0,
    baseMagic: 0,
    health: 4,
    shield: 0,
    speed: 2,
    baseHealth: 4,
    baseShield: 0,
    cost: 4,
  },
  {
    id: "2",
    name: "Goblin",
    attack: 3,
    magic: 0,
    baseMagic: 0,
    health: 5,
    shield: 0,
    speed: 2,
    baseHealth: 5,
    baseShield: 0,
    cost: 6,
  },
  {
    id: "3",
    name: "Orc",
    attack: 4,
    magic: 0,
    baseMagic: 0,
    health: 7,
    shield: 0,
    speed: 2,
    baseHealth: 7,
    baseShield: 0,
    cost: 8,
  },
  {
    id: "4",
    name: "Caçador Orc",
    attack: 4,
    magic: 0,
    baseMagic: 0,
    health: 7,
    shield: 0,
    speed: 2,
    baseHealth: 7,
    baseShield: 0,
    cost: 10,
  },
  {
    id: "5",
    name: "Fera",
    attack: 4,
    magic: 0,
    baseMagic: 0,
    health: 10,
    shield: 0,
    speed: 3,
    baseHealth: 10,
    baseShield: 0,
    cost: 12,
  },
  {
    id: "6",
    name: "Espectro",
    attack: 5,
    magic: 0,
    baseMagic: 0,
    health: 12,
    shield: 0,
    speed: 2,
    baseHealth: 12,
    baseShield: 0,
    cost: 14,
  },
  {
    id: "7",
    name: "Troll",
    attack: 6,
    magic: 0,
    baseMagic: 0,
    health: 13,
    shield: 0,
    speed: 1,
    baseHealth: 13,
    baseShield: 0,
    cost: 16,
  },
];
